### ISSUE TITLE
In Auto PRs only commit type changes

### ISSUE THREAD

**Issue by Maxim-Mazurok** [Maxim-Mazurok/google-api-typings-generator#124]
Don't commit changes from other types.
Our update mechanism doesn't work correctly. It treats branch updates to master as new commits which is not good.

Example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43734
When merging, it only affects our files, but commits contain modifications in other types, which confuses DT bot: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43734#event-3215091972

Another example: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...Maxim-Mazurok:gapi.client.sheets
It should not show changes in other types. And our branches should only be ahead of master, not `4 commits ahead, 23 commits behind DefinitelyTyped:master.`

**Comment by namoscato** [comment]
> And our branches should only be ahead of master, not `4 commits ahead, 23 commits behind DefinitelyTyped:master.`

I imagine this is due to some of the git magic / forcing?

Could we just disable updates to existing DT PRs for now?

**Comment by Maxim-Mazurok** [comment]
That's actually happens when branch already exists. And it basically every single type after the first run.
I'm going to figure this out on the weekend. I think I have to properly merge or rebase master into the type branch.

**Comment by Maxim-Mazurok** [comment]
Here's my understanding of shat happened and what we should do instead:
![Drawing](https://user-images.githubusercontent.com/7756211/78902355-089aed00-7abd-11ea-8157-f9d9caf8e4e0.png)
