### ISSUE TITLE
Skip revision-only updates

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#138]
I'm not sure I see the value in updating types when there is only a revision number change. Thoughts?

**Comment by Maxim-Mazurok** [comment]
Well, if it was fully automated from both our and DT side, it wouldn't hurt. But since it still takes a real DT maintainer effort to merge it, probably we should indeed skip such updates.
Ideally, we would still publish it too types branch, and don't publish to DT.
