### ISSUE TITLE
Add required status checks to master

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#32]
If you have not already, can you require the `test` and `lint` status checks for `master`?

It will look something like this under **Settings > Branches**:

<img width="771" alt="Screen Shot 2020-01-08 at 8 16 32 PM" src="https://user-images.githubusercontent.com/847532/72029388-c7900400-3253-11ea-9d9c-8d256a6cb66a.png">

**Comment by Maxim-Mazurok** [comment]
Done, thanks :+1:
