### ISSUE TITLE
Issues with "analyticsreporting" type definitions

### ISSUE THREAD

**Issue by hakimio** [Maxim-Mazurok/google-api-typings-generator#363]
There are a couple of issues with Analytics reporting definitions:
- [gapi.client.analyticsreporting.reports.batchGet()](https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/types/gapi.client.analyticsreporting/index.d.ts#L662) parameter type is not correct.
According to [official documentation](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet) it should be the following:
```ts
batchGet(request: GetReportsRequest): Request<GetReportsResponse>;
```
- The return type is not correct as well. It should be `HttpRequest<GetReportsResponse>` instead of `Request<GetReportsResponse>`.

Also as a side-note, following doc comment is not correct either:
```ts
/// <reference types="gapi.client" />
```
It should be:
```ts
/// <reference types="gapi" />
```

**Comment by Maxim-Mazurok** [comment]
Thanks for reporting this!

> gapi.client.analyticsreporting.reports.batchGet() parameter type is not correct.

Have you tried to use something like this?
```js
batchGet({
  request: { /* ... */ },
  body: {
    "reportRequests": [
      {
        // object(ReportRequest)
      }
    ],
    "useResourceQuotas": true // or false
  }
});
```

Regarding `HttpRequest` vs `Request` and `gapi.client` vs `gapi`, please note that there are two very similar types:
`@types/gapi` and `@types/gapi.client`.
This project uses and maintains `@types/gapi.client`. If you want to help, check out this project: https://github.com/Maxim-Mazurok/gapi

So, if you'd like to use these types, you probably should remove `@types/gapi` and use `@types/gapi.client` instead.

Also, I want to confirm that you're using this API on the client-side, and not in NodeJS, is that right?

And if you have any example code that you can share- it would be a great help!

**Comment by Maxim-Mazurok** [comment]
I created an example here: https://gist.github.com/Maxim-Mazurok/84fcbe394ea289531c3ad4fa1d293cf0

Here's how you can use current types:
```js
await gapi.client.analyticsreporting.reports.batchGet({
  resource: {
    reportRequests: [
      {
        viewId: 'VIEW_ID',
        dateRanges: [
          {
            startDate: '7daysAgo',
            endDate: 'today',
          },
        ],
        metrics: [
          {
            expression: 'ga:sessions',
          },
        ],
      },
    ],
  },
});
```

For some reason, [`body` approach](https://github.com/Maxim-Mazurok/google-api-typings-generator/tree/master#resource-vs-body) doesn't work for this API.

I have created #364 to allow simpler syntax usage.

I will also include this API into our auto-update script so that you will able to use it from NPM.

Please, let me know if my solution worked for you!

**Comment by Maxim-Mazurok** [comment]
This type was merged to DT and will be published to NPM shortly :)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48121

**Comment by hakimio** [comment]
Yes, I am running it on client side (browser). 
I am using `gapi.client.analyticsreporting.reports.batchGet()` the way it's described in the [official Google documentation](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet):
```ts
await gapi.client.analyticsreporting.reports.batchGet({
    reportRequests: [
      {
        viewId: 'VIEW_ID',
        dateRanges: [
          {
            startDate: '7daysAgo',
            endDate: 'today',
          }
        ],
        metrics: [
          {
            expression: 'ga:sessions',
          }
        ]
      }
    ]
});
```
Where do you get your `resource` property from?

**Comment by hakimio** [comment]
Also, if you look at the [Google JavaScript examples](https://developers.google.com/analytics/devguides/reporting/core/v4/samples), that's how they calling `batchGet()` there as well.

**Comment by Maxim-Mazurok** [comment]
Sure, let me try to explain this :)
Google has a number of ways to send requests. Because sometimes you just want to send the "main" a.k.a "resource" parameters.
But sometimes, you need a way to specify [other fields as well](https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/types/gapi.client.analyticsreporting/index.d.ts#L636-L661). For example, `access_token`. 

Here's a part of the source code, where google handles your "resource" field:
![image](https://user-images.githubusercontent.com/7756211/94114307-84320000-fe8b-11ea-990b-9ab121ad74c3.png)

It's really hard to read because it's minified (and that's why I started [gapi](https://github.com/Maxim-Mazurok/gapi) project). But basically, it checks if there's a "resource" field in the request and if it is - it uses it's value as a payload. Otherwise, it will use the whole object as a payload (in the "direct" case).

So, your approach (the one you saw in the docs) is totally fine and it works. But it doesn't work with our type definitions (yet). It will work after I fix it in #364.

I hope it makes sense now, let me know if you have any other questions!

**Comment by hakimio** [comment]
Ok, it makes perfect sense. Thanks for taking your time to explain it. I'll close this in favor of #364 .

BTW, does Google license allow reverse engineering their proprietary "gapi" library?

**Comment by Maxim-Mazurok** [comment]
No worries, I was glad to help :)

Regarding the gapi library, I'm studying how it's built for a personal research purposes, not for commercial use, so I don't think that there will be any problem. But it's a good question, if you feel adventurous - you can take a look at their license agreement and do a little research, that will be helpful :)
I'm not so sawy in licenses, so I just do my research with good faith and don't expect to be punished, but will definitely delete everything and stop the research in case if I'm asked to do so.

**Comment by hakimio** [comment]
It seems to be licensed under "Apache 2.0" license. So, you should be free to do whatever you want as long as you keep all "copyright, patent, trademark, and attribution notices":
```
   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.
```

**Comment by Maxim-Mazurok** [comment]
You are probably referring to the license of this project: https://github.com/google/google-api-javascript-client

But it doesn't contain the actual source code of GAPI: https://github.com/google/google-api-javascript-client/issues/669

And it looks like we're not going to have it for a while: https://github.com/google/google-api-javascript-client/issues/432#issuecomment-435523106

**Comment by hakimio** [comment]
@Maxim-Mazurok if you open [this link](https://apis.google.com/js/api.js), you'll see the following comment:
```
/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
```
That's why I assume it's licensed under Apache license.

**Comment by Maxim-Mazurok** [comment]
Right, it is generated by [google/closure-library](https://github.com/google/closure-library/), which is under Apache, so I guess that the results of this generation are also under Apache... 
And it says
> You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use

So, I guess it's OK that my gapi research project is under MIT license.
Thanks for the investigation, much appreciated!

**Comment by hakimio** [comment]
@Maxim-Mazurok can you create a PR in `DefinitelyTyped` project for `@types/gapi.client.analytics`? They have [data, management, metadata and provisioning properties defined](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gapi.client.analytics/index.d.ts#L19) under wrong namespace. They should be inside of "analytics" namespace instead of "gapi.client".
Or should I do it?
Also, is there any simple way to use your auto-generated types from "types" branch directly as npm dependency?

**Comment by Maxim-Mazurok** [comment]
@hakimio please open new issue next time, I almost missed this comment...
We have an automated process in place for opening PRs to DT and keeping all type definitions up to date.
Currently, only some packages are included in this process: https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/bin/auto-update/config.ts
I'll add `analytics` to the list, or next time you can also create PR to add it.

Regarding usage of types branch, you can refer to [this comment](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601133279). You can try `npm install https://github.com/Maxim-Mazurok/google-api-typings-generator#types`, but it was never intended for such use... 

Your best bet is to use types from DT, once I add `analytics` to the list. Now all PRs are getting merged automatically, so it's just as fresh as our types branch. Maybe about an hour older, but that should not make much difference.

**Comment by Maxim-Mazurok** [comment]
Please, approve/upvote this PR to enable auto-updates for `gapi.client.analytics` in DT.
After we take over ownership - updates will be instant.

**Comment by hakimio** [comment]
@Maxim-Mazurok Thanks for creating the PR.
I didn't want to create a new issue here since there is nothing wrong with the typings you have in this repository.

**Comment by Maxim-Mazurok** [comment]
Thank you :) Issues here are just like work items, tasks or questions. When you open issues it doesn't necessarily mean that there's something wrong :)
Open issue would give better visibility, that's why it's preferred.
Glad I could help :)
