### ISSUE TITLE
Include API revision number in generated type definition comment

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#45]
Let's add a new comment line, like this:
```js
// Generated from: https://sheets.googleapis.com/$discovery/rest?version=v4
// Revision: 20191204
```
And we could easily parse it using [`/^\/\/ Revision: (\d{8})$/gm`](https://regex101.com/r/LfWrDx/1)

_Originally posted by @Maxim-Mazurok in https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/15#issuecomment-573295537_

**Comment by namoscato** [comment]
I can probably grab this one soon.

**Comment by Maxim-Mazurok** [comment]
Sounds good, thank you!
I just moved to Sydney and had to set up everything basic, like mobile number, bank account, etc. Now I have more time to dedicate to this project. First I will fix CI and then I'll work on automatic updates, ok?
