### ISSUE TITLE
Unclear how to use new types

### ISSUE THREAD

**Issue by bamnet** [Maxim-Mazurok/google-api-typings-generator#483]
I'm trying to import types that have been generated for `gapi.client.apikeys` which I see are available at https://github.com/Maxim-Mazurok/google-api-typings-generator/tree/types/gapi.client.apikeys/. This looks like a much better system then manually trying to create some typings based on the documentation / discovery document.

Following the instructions on that README page (`npm install @types/gapi.client.apikeys@v2 --save-dev`), I get an error that the type isn't published.  Is there a different process to install these typings?

```
$ npm install @types/gapi.client.apikeys@v2 --save-dev
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fgapi.client.apikeys - Not found
npm ERR! 404 
npm ERR! 404  '@types/gapi.client.apikeys@v2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by Maxim-Mazurok** [comment]
Hello! Not all types in this repository are added to DefinitelyTyped and published to npm (see #401). I'll update types list shortly and will let you know. Meanwhile, you can download d.ts file and put it in your project folder.

**Comment by Maxim-Mazurok** [comment]
Published to NPM: [@maxim_mazurok/gapi.client.apikeys](https://www.npmjs.com/package/@maxim_mazurok/gapi.client.apikeys), feel free to use it for now (`npm install @maxim_mazurok/gapi.client.apikeys`)

`@types/gapi.client.apikeys` will mirror this package, once https://github.com/microsoft/DefinitelyTyped-tools/pull/240 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52618 are merged.

**Comment by Maxim-Mazurok** [comment]
Please, consider giving the project a "star" if you like it 😜

**Comment by bamnet** [comment]
Thanks for the quick workaround!

**Comment by Maxim-Mazurok** [comment]
You're welcome! I've added info about this error to the docs in #485, which will close this issue once merged. Cheers!

**Comment by Maxim-Mazurok** [comment]
@bamnet https://www.npmjs.com/package/@types/gapi.client.apikeys was just published, feel free to use it :)

**Comment by bamnet** [comment]
Woohoo, thanks so much!!! :partying_face:
