### ISSUE TITLE
Add Google Ads API

### ISSUE THREAD

**Issue by davecardwell** [Maxim-Mazurok/google-api-typings-generator#499]
The Google Ads API has a [discovery document](https://googleads.googleapis.com/$discovery/rest?version=v7) available but it is not listed in the [googleapis.com API list](https://www.googleapis.com/discovery/v1/apis) for some reason.

I can generate the types manually using `npm start -- --url https://googleads.googleapis.com/\\\$discovery/rest?version=v7` but couldn’t see any way of adding it to the automated generating/linting/testing/publishing pipeline.

For APIs that are not listed in the API list am I best off adding directly to DefinitelyTyped or is there a simple way to support hard-coded discovery doc URLs in this project?

**Comment by Maxim-Mazurok** [comment]
Hello Dave!
Hm, it's a very good find, thanks for that.
For sure it's better to add this to the CI pipeline.
I will try to add it today.
BTW, where did you find [that](https://googleads.googleapis.com/$discovery/rest?version=v7) URL?

**Comment by Maxim-Mazurok** [comment]
@davecardwell I've included googleads API to the CI. And opened PRs to add it to DT.
For now, you can use it from https://www.npmjs.com/package/@maxim_mazurok/gapi.client.googleads
It'll get hourly updates as all other API types from now on.
Let me know if there's anything else I can help you with :)
And please, consider giving this repo a star if you found it useful ;)

**Comment by davecardwell** [comment]
@Maxim-Mazurok awesome turnaround, thank you.

I honestly can’t remember where I found the discovery doc originally, sorry!

**Comment by Maxim-Mazurok** [comment]
@davecardwell https://www.npmjs.com/package/@types/gapi.client.googleads just got published, feel free to replace `@maxim_mazurok/gapi.client.googleads` with `@types/gapi.client.googleads`. Cheers!

**Comment by Maxim-Mazurok** [comment]
@davecardwell Hello Dave, I see that the current Google Ads API version is 11, and we're still only publishing types for version 7... I'm working on multiple versions support for #652 and just wanted to confirm with you that you are/were using Google Ads on the client-side (front-end)?

**Comment by Maxim-Mazurok** [comment]
@davecardwell I did some digging trying to make Google Ads API work with Gapi Client, but no luck so far...

I can get as far as making a valid request but getting this error:
```js
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.ads.googleads.v11.errors.GoogleAdsFailure",
        "errors": [
          {
            "errorCode": {
              "requestError": "DEVELOPER_TOKEN_PARAMETER_MISSING"
            },
            "message": "developer-token parameter is missing."
          }
        ],
        "requestId": "MxqnpWl7Y1_0_f183FepRg"
      }
    ]
  }
}
```

If I copy request from devtools and add `developer-token` - it works.

The only way I could find to specify `developer-token` is by using `gapi.client.request` with `headers` option, but then I'm getting 404 for some reason...

I've been trying to do it like this:
```ts
const DISCOVERY_DOCS = ["https://googleads.googleapis.com/$discovery/rest?version=v11"];
const SCOPE = "https://www.googleapis.com/auth/adwords";
//...
gapi.client
  .request({
    path: "https://content-googleads.googleapis.com/v11/geoTargetConstants:suggest",
    body: {
      geoTargets: { geoTargetConstants: ["20118"] },
      countryCode: "AU",
    },
    headers: { "developer-token": "HoNg7IWmGKmjJT5GlGv0Yg" },
  })
```

I also tried overriding `XMLHttpRequest.send()` but it's no use because actual requests are being sent from the iframe that gapi adds dynamically...

Please give me some pointers on how you used these types for Google Ads 🙏

**Comment by davecardwell** [comment]
@Maxim-Mazurok I was using it on the front-end. Unfortunately I don’t recall the exact method and I have moved on from that company so no longer have access to the project to check.

**Comment by Maxim-Mazurok** [comment]
I see, thanks anyway for confirming, since it can be used on FE - I'll make sure we keep on generating types for it, cheers!
