### ISSUE TITLE
Only publish new revisions on build

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#81]
It would be much easier if we just check during generation/publication to `types` branch is we're publishing revision which is never than current revision. So it will never decrease.

_Originally posted by @Maxim-Mazurok in https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/74_

**Comment by namoscato** [comment]
I can try to get to this guy soon.

**Comment by Maxim-Mazurok** [comment]
I expect this one to be a bit complex. At some point of build process we would have to clone/zip-download types branch to extract revision dates and compare them to the types being generated/published. So it's quite different from current approach and may require some custom bash-scripting. Let me know if you'll need any assistance on this one. Also, you can refer to #74 code which has some nice git tricks.

**Comment by namoscato** [comment]
Yeah, good point. Admittedly, I haven't given this much thought yet but will plan to jot down an approach before I get too far along.
