### ISSUE TITLE
Configure Dependabot

### ISSUE THREAD

**Issue by namoscato** [Maxim-Mazurok/google-api-typings-generator#9]
I've been using [Dependabot](https://dependabot.com/) for a lot of my projects recently. Thoughts on configuring this project to use it?

**Comment by Maxim-Mazurok** [comment]
Sure, good idea! I've added it for this repo with default JS config. Feel free to open PR with `.dependabot/config.yml` as I'm not a heavy dependabot user, I could use your help setting it up the right way.

**Comment by namoscato** [comment]
> I've added it for this repo with default JS config.

That's fine by me – thanks!
