### ISSUE TITLE
Publish typings to the repository's GitHub Packages

### ISSUE THREAD

**Issue by Maxim-Mazurok** [Maxim-Mazurok/google-api-typings-generator#90]
What about publishing the typings to the repository's [GitHub Packages](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages)?

From the documentation:

> By default, GitHub Packages publishes a package in the GitHub repository you specify in the name field of the package.json file. For example, you would publish a package named `@my-org/test` to the `my-org/test` GitHub repository.

_Originally posted by @EdricChan03 in https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/85#issuecomment-601144855_

I think we can do this for "nightly" builds, that will be published without any manual reviews by DefinetlyTyped team.

TODO:
- [ ] Update PR line regarding using nightly types: https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/74#discussion_r399916523

**Comment by namoscato** [comment]
Definitely a cool idea and worth messing with if it would be straightforward to implement.

My two cents: I feel like this could quickly evolve into reinventing the wheel that DefinitelyTyped has already got going around package management. It also might be confusing to have multiple type definition packages for the same Google service longterm.

_Sidenote: I wonder what will happen to GitHub Packages now that they [acquired npm](https://github.blog/2020-03-16-npm-is-joining-github/) 🤔._

**Comment by Maxim-Mazurok** [comment]
Yes, I think it should be as easy as possible, so that we don't have to reinvent the DT wheel :)
While I agree that confusion is possible, form my understanding of GH packages, they are not published to main NPM directory, but rather to GH directory. So default choice would be to use NPM and if somebody really want to - he can use nightly builds from GH. Hopefully it will not create much confusion.
I don't expect anything radical or bad happening to GH packages in lights of this accusation. 
If you want to mess around with this idea - feel free to self-assign this :)

**Comment by Maxim-Mazurok** [comment]
This will be closed by https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/391
And we're going to use NPM, because I can see no particular value in publishing to another registry.
