### ISSUE TITLE
Create list of supported APIs

### ISSUE THREAD

**Issue by Maxim-Mazurok** [Maxim-Mazurok/google-api-typings-generator#97]
We should create a curated list of supported APIs that actually need our typings.
Our main focus should be on APIs that have client (browser) library.

**Comment by namoscato** [comment]
Where did we land with this behavior in the current state of `master`? Did we scope things to `sheets`?

**Comment by Maxim-Mazurok** [comment]
Currently we have blacklist for generated types and whitelist for types that we want to open new PRs. This whitelist currently contains only `sheets`, yes.
I have temporarily disabled auto PRs by revoking access token, because of #124

**Comment by Maxim-Mazurok** [comment]
This issue is suppressed by #401 because now we're supporting all APIs by default, and exclude some that are particularly difficult to handle right now.
